// Cloudflare Worker - Wasabi Video Streaming Player
// Deploy this worker to serve video files from Wasabi with an elegant player UI

// ============ CONFIGURATION ============
const WASABI_CONFIG = {
    accessKey: "YOUR_WASABI_ACCESS_KEY",     // Set via secrets
    secretKey: "YOUR_WASABI_SECRET_KEY",     // Set via secrets
    bucket: "your-bucket-name",
    region: "us-east-1",                     // e.g., us-east-1, eu-central-1
    endpoint: "https://s3.wasabisys.com"     // Standard Wasabi endpoint
};

// Alternative: Use environment variables in Cloudflare dashboard
// Bind these as secrets: WASABI_ACCESS_KEY, WASABI_SECRET_KEY, WASABI_BUCKET, WASABI_REGION

// Supported video formats for streaming
const SUPPORTED_VIDEO_FORMATS = ['.mp4', '.mkv', '.webm', '.mov', '.avi', '.m4v', '.mpg', '.mpeg'];

// CORS headers for cross-origin requests
const CORS_HEADERS = {
    'Access-Control-Allow-Origin': '*',
    'Access-Control-Allow-Methods': 'GET, HEAD, OPTIONS',
    'Access-Control-Allow-Headers': 'Range, Content-Type, Origin',
    'Access-Control-Expose-Headers': 'Content-Length, Content-Range, Accept-Ranges'
};

// ============ HELPER FUNCTIONS ============

/**
 * Generate AWS Signature V4 for Wasabi/S3 authentication
 */
async function signRequest(method, url, headers = {}, body = null) {
    // For presigned URLs or direct access, we use simpler approach
    // This worker can either:
    // 1. Proxy requests with AWS Signature (recommended for security)
    // 2. Use presigned URLs generated by your bot (simpler)
    
    const accessKey = WASABI_CONFIG.accessKey || env.WASABI_ACCESS_KEY;
    const secretKey = WASABI_CONFIG.secretKey || env.WASABI_SECRET_KEY;
    
    if (!accessKey || !secretKey) {
        console.error("Missing Wasabi credentials");
        return null;
    }
    
    // Parse URL
    const parsedUrl = new URL(url);
    const region = WASABI_CONFIG.region || env.WASABI_REGION || 'us-east-1';
    const service = 's3';
    const host = parsedUrl.hostname;
    
    const now = new Date();
    const amzDate = now.toISOString().replace(/[:\-]|\.\d{3}/g, '');
    const dateStamp = amzDate.slice(0, 8);
    
    // Create canonical request
    const canonicalHeaders = `host:${host}\nx-amz-date:${amzDate}\n`;
    const signedHeaders = 'host;x-amz-date';
    
    let canonicalRequest = `${method}\n${parsedUrl.pathname}\n${parsedUrl.searchParams.toString()}\n${canonicalHeaders}\n${signedHeaders}\nUNSIGNED-PAYLOAD`;
    
    // Create string to sign
    const algorithm = 'AWS4-HMAC-SHA256';
    const credentialScope = `${dateStamp}/${region}/${service}/aws4_request`;
    const stringToSign = `${algorithm}\n${amzDate}\n${credentialScope}\n${await sha256(canonicalRequest)}`;
    
    // Calculate signature
    const signature = await calculateSignature(secretKey, dateStamp, region, service, stringToSign);
    
    // Create authorization header
    const authorization = `${algorithm} Credential=${accessKey}/${credentialScope}, SignedHeaders=${signedHeaders}, Signature=${signature}`;
    
    return {
        'Authorization': authorization,
        'x-amz-date': amzDate,
        'Host': host
    };
}

/**
 * SHA256 hash helper
 */
async function sha256(message) {
    const encoder = new TextEncoder();
    const data = encoder.encode(message);
    const hash = await crypto.subtle.digest('SHA-256', data);
    return Array.from(new Uint8Array(hash))
        .map(b => b.toString(16).padStart(2, '0'))
        .join('');
}

/**
 * HMAC-SHA256 calculation for AWS signature
 */
async function hmacSha256(key, message) {
    const encoder = new TextEncoder();
    const keyData = typeof key === 'string' ? encoder.encode(key) : key;
    const messageData = encoder.encode(message);
    const cryptoKey = await crypto.subtle.importKey('raw', keyData, { name: 'HMAC', hash: 'SHA-256' }, false, ['sign']);
    const signature = await crypto.subtle.sign('HMAC', cryptoKey, messageData);
    return new Uint8Array(signature);
}

async function calculateSignature(secretKey, dateStamp, region, service, stringToSign) {
    const kSecret = `AWS4${secretKey}`;
    const kDate = await hmacSha256(kSecret, dateStamp);
    const kRegion = await hmacSha256(kDate, region);
    const kService = await hmacSha256(kRegion, service);
    const kSigning = await hmacSha256(kService, 'aws4_request');
    const signature = await hmacSha256(kSigning, stringToSign);
    return Array.from(signature).map(b => b.toString(16).padStart(2, '0')).join('');
}

/**
 * Generate a presigned URL for direct Wasabi access
 */
async function generatePresignedUrl(key, expiresIn = 3600) {
    const accessKey = WASABI_CONFIG.accessKey || env.WASABI_ACCESS_KEY;
    const secretKey = WASABI_CONFIG.secretKey || env.WASABI_SECRET_KEY;
    const bucket = WASABI_CONFIG.bucket || env.WASABI_BUCKET;
    const region = WASABI_CONFIG.region || env.WASABI_REGION || 'us-east-1';
    const endpoint = WASABI_CONFIG.endpoint || 'https://s3.wasabisys.com';
    
    if (!accessKey || !secretKey) {
        return null;
    }
    
    const method = 'GET';
    const host = `${bucket}.s3.${region}.wasabisys.com`;
    const url = new URL(`https://${host}/${encodeURIComponent(key)}`);
    
    const now = new Date();
    const amzDate = now.toISOString().replace(/[:\-]|\.\d{3}/g, '');
    const dateStamp = amzDate.slice(0, 8);
    const expires = expiresIn;
    
    // Add query parameters for presigned URL
    url.searchParams.set('X-Amz-Algorithm', 'AWS4-HMAC-SHA256');
    url.searchParams.set('X-Amz-Credential', `${accessKey}/${dateStamp}/${region}/s3/aws4_request`);
    url.searchParams.set('X-Amz-Date', amzDate);
    url.searchParams.set('X-Amz-Expires', expires.toString());
    url.searchParams.set('X-Amz-SignedHeaders', 'host');
    
    // Create canonical request for presigned URL
    const canonicalHeaders = `host:${host}\n`;
    const signedHeaders = 'host';
    const canonicalRequest = `${method}\n/${encodeURIComponent(key)}\n${url.searchParams.toString()}\n${canonicalHeaders}\n${signedHeaders}\nUNSIGNED-PAYLOAD`;
    
    const stringToSign = `AWS4-HMAC-SHA256\n${amzDate}\n${dateStamp}/${region}/s3/aws4_request\n${await sha256(canonicalRequest)}`;
    
    const signature = await calculateSignature(secretKey, dateStamp, region, 's3', stringToSign);
    url.searchParams.set('X-Amz-Signature', signature);
    
    return url.toString();
}

/**
 * Check if file is a video based on extension
 */
function isVideoFile(filename) {
    const ext = filename.toLowerCase().substring(filename.lastIndexOf('.'));
    return SUPPORTED_VIDEO_FORMATS.includes(ext);
}

/**
 * Format bytes to human readable
 */
function formatBytes(bytes) {
    if (bytes === 0) return '0 Bytes';
    const k = 1024;
    const sizes = ['Bytes', 'KB', 'MB', 'GB', 'TB'];
    const i = Math.floor(Math.log(bytes) / Math.log(k));
    return parseFloat((bytes / Math.pow(k, i)).toFixed(2)) + ' ' + sizes[i];
}

/**
 * Extract filename from path or query
 */
function getFilenameFromPath(pathname) {
    const decoded = decodeURIComponent(pathname);
    const parts = decoded.split('/');
    let filename = parts.pop() || 'video';
    // Remove query params if any
    filename = filename.split('?')[0];
    return filename;
}

// ============ HTML PLAYER TEMPLATE ============

function getPlayerHTML(videoUrl, filename, fileSize = null) {
    const fileType = isVideoFile(filename) ? 'video' : 'other';
    const displayName = filename.length > 50 ? filename.substring(0, 47) + '...' : filename;
    const sizeText = fileSize ? ` • ${formatBytes(fileSize)}` : '';
    
    return `<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, viewport-fit=cover">
    <title>Wasabi Stream · ${escapeHtml(displayName)}</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css">
    <style>
        * {
            margin: 0;
            padding: 0;
            box-sizing: border-box;
        }
        
        body {
            background: linear-gradient(135deg, #0a0c12 0%, #0f111a 100%);
            font-family: -apple-system, BlinkMacSystemFont, 'Inter', 'Segoe UI', Roboto, Helvetica, sans-serif;
            min-height: 100vh;
            display: flex;
            justify-content: center;
            align-items: center;
            padding: 1rem;
        }
        
        .player-card {
            max-width: 1300px;
            width: 100%;
            background: rgba(18, 22, 35, 0.85);
            backdrop-filter: blur(16px);
            border-radius: 2rem;
            overflow: hidden;
            box-shadow: 0 25px 50px -12px rgba(0, 0, 0, 0.5), 0 0 0 1px rgba(255, 255, 255, 0.05);
        }
        
        .video-container {
            position: relative;
            background: #000;
            width: 100%;
            aspect-ratio: 16 / 9;
            background-color: #0b0e16;
        }
        
        video {
            width: 100%;
            height: 100%;
            display: block;
            object-fit: contain;
        }
        
        .info-section {
            padding: 1.5rem 2rem 2rem;
        }
        
        .badge {
            display: inline-flex;
            align-items: center;
            gap: 0.5rem;
            background: #1e293b;
            padding: 0.3rem 1rem;
            border-radius: 40px;
            font-size: 0.75rem;
            font-weight: 600;
            color: #8b9eff;
            margin-bottom: 1rem;
        }
        
        h1 {
            font-size: 1.5rem;
            font-weight: 600;
            background: linear-gradient(135deg, #fff, #a5b4fc);
            background-clip: text;
            -webkit-background-clip: text;
            color: transparent;
            word-break: break-word;
        }
        
        .filename-display {
            background: #0f111f;
            padding: 0.7rem 1rem;
            border-radius: 1rem;
            font-family: monospace;
            font-size: 0.8rem;
            color: #9ca3cf;
            margin: 1rem 0;
            word-break: break-all;
        }
        
        .button-group {
            display: flex;
            flex-wrap: wrap;
            gap: 0.8rem;
            margin-top: 1rem;
        }
        
        .btn {
            display: inline-flex;
            align-items: center;
            gap: 0.6rem;
            padding: 0.7rem 1.5rem;
            border-radius: 40px;
            font-weight: 600;
            font-size: 0.9rem;
            text-decoration: none;
            cursor: pointer;
            transition: all 0.2s ease;
            border: none;
            font-family: inherit;
        }
        
        .btn-primary {
            background: #3b4f8c;
            color: white;
        }
        
        .btn-primary:hover {
            background: #4f68b0;
            transform: translateY(-2px);
        }
        
        .btn-outline {
            background: transparent;
            border: 1px solid #4e5b8e;
            color: #d9e2ff;
        }
        
        .btn-outline:hover {
            background: #2a2f4e;
            border-color: #7c8ed6;
        }
        
        .info-note {
            margin-top: 1.5rem;
            padding: 0.7rem 1rem;
            background: #10131f;
            border-left: 4px solid #4c7bd9;
            border-radius: 1rem;
            font-size: 0.75rem;
            color: #a8b3e0;
            display: flex;
            align-items: center;
            gap: 0.5rem;
        }
        
        .error-state {
            text-align: center;
            padding: 3rem;
        }
        
        .error-state i {
            font-size: 4rem;
            color: #f87171;
            margin-bottom: 1rem;
        }
        
        footer {
            text-align: center;
            padding: 1rem;
            font-size: 0.7rem;
            color: #5c689b;
            border-top: 1px solid rgba(255, 255, 255, 0.05);
        }
        
        @media (max-width: 640px) {
            .info-section { padding: 1rem; }
            h1 { font-size: 1.2rem; }
            .btn { padding: 0.5rem 1rem; font-size: 0.8rem; }
        }
    </style>
</head>
<body>
    <div class="player-card">
        <div class="video-container">
            ${fileType === 'video' ? 
                `<video id="videoPlayer" controls playsinline preload="metadata">
                    <source src="${escapeHtml(videoUrl)}" type="video/mp4">
                    Your browser does not support video playback.
                </video>` : 
                `<div class="error-state">
                    <i class="fas fa-file-alt"></i>
                    <h3>File Preview Unavailable</h3>
                    <p style="margin-top: 0.5rem;">This file type cannot be streamed directly.</p>
                    <a href="${escapeHtml(videoUrl)}" class="btn btn-primary" style="margin-top: 1.5rem; display: inline-flex;">
                        <i class="fas fa-download"></i> Download File
                    </a>
                </div>`
            }
        </div>
        <div class="info-section">
            <div class="badge">
                <i class="fas ${fileType === 'video' ? 'fa-video' : 'fa-cloud-download-alt'}"></i>
                <span>${fileType === 'video' ? 'Streaming Ready' : 'Direct Download'}</span>
            </div>
            <h1>🎬 ${escapeHtml(displayName)}</h1>
            <div class="filename-display">
                <i class="far fa-file"></i> ${escapeHtml(filename)}${sizeText}
            </div>
            <div class="button-group">
                <a href="${escapeHtml(videoUrl)}" class="btn btn-primary" download>
                    <i class="fas fa-download"></i> Download
                </a>
                <button class="btn btn-outline" id="copyDirectBtn">
                    <i class="far fa-copy"></i> Copy Link
                </button>
                <button class="btn btn-outline" id="copyPlayerBtn">
                    <i class="fas fa-link"></i> Share Player
                </button>
            </div>
            <div class="info-note">
                <i class="fas fa-bolt"></i>
                <span>⚡ Direct Wasabi streaming • 7-day validity • Optimized for 4K</span>
            </div>
        </div>
        <footer>
            <i class="fas fa-shield-alt"></i> Secured by Wasabi + Cloudflare Worker
        </footer>
    </div>
    <script>
        const videoUrl = "${escapeHtml(videoUrl)}";
        
        document.getElementById('copyDirectBtn')?.addEventListener('click', async () => {
            try {
                await navigator.clipboard.writeText(videoUrl);
                showToast('✓ Direct link copied!');
            } catch(e) {
                prompt('Copy URL:', videoUrl);
            }
        });
        
        document.getElementById('copyPlayerBtn')?.addEventListener('click', async () => {
            try {
                await navigator.clipboard.writeText(window.location.href);
                showToast('✓ Player link copied!');
            } catch(e) {
                prompt('Copy URL:', window.location.href);
            }
        });
        
        function showToast(msg) {
            const toast = document.createElement('div');
            toast.textContent = msg;
            toast.style.position = 'fixed';
            toast.style.bottom = '20px';
            toast.style.left = '50%';
            toast.style.transform = 'translateX(-50%)';
            toast.style.backgroundColor = '#1f2b4e';
            toast.style.color = 'white';
            toast.style.padding = '10px 20px';
            toast.style.borderRadius = '40px';
            toast.style.fontSize = '0.85rem';
            toast.style.zIndex = '10000';
            toast.style.backdropFilter = 'blur(12px)';
            document.body.appendChild(toast);
            setTimeout(() => toast.remove(), 2500);
        }
        
        // Video quality detection
        const video = document.getElementById('videoPlayer');
        if (video) {
            video.addEventListener('error', () => {
                console.error('Video failed to load');
            });
        }
    </script>
</body>
</html>`;
}

function escapeHtml(str) {
    if (!str) return '';
    return str.replace(/[&<>]/g, function(m) {
        if (m === '&') return '&amp;';
        if (m === '<') return '&lt;';
        if (m === '>') return '&gt;';
        return m;
    }).replace(/[\uD800-\uDBFF][\uDC00-\uDFFF]/g, function(c) {
        return c;
    });
}

// ============ MAIN WORKER HANDLER ============

export default {
    async fetch(request, env, ctx) {
        const url = new URL(request.url);
        const path = url.pathname;
        
        // Handle CORS preflight
        if (request.method === 'OPTIONS') {
            return new Response(null, { headers: CORS_HEADERS });
        }
        
        // Health check endpoint
        if (path === '/health' || path === '/') {
            return new Response(JSON.stringify({
                status: 'healthy',
                service: 'wasabi-stream-worker',
                timestamp: new Date().toISOString()
            }), {
                headers: { 'Content-Type': 'application/json', ...CORS_HEADERS }
            });
        }
        
        // Player route: /player/:encodedUrl or /player?url=...
        if (path.startsWith('/player') || path === '/watch') {
            let videoUrl = null;
            let filename = url.searchParams.get('name') || 'video.mp4';
            
            // Check for encoded URL parameter
            if (url.searchParams.has('url')) {
                videoUrl = decodeURIComponent(url.searchParams.get('url'));
            } 
            // Check for path-based encoded URL: /player/encodedBase64Url
            else if (path.startsWith('/player/')) {
                const encoded = path.substring(8);
                try {
                    // Support base64url encoded strings
                    let base64 = encoded.replace(/-/g, '+').replace(/_/g, '/');
                    while (base64.length % 4) base64 += '=';
                    videoUrl = atob(base64);
                } catch (e) {
                    videoUrl = decodeURIComponent(encoded);
                }
            }
            
            if (!videoUrl) {
                return new Response(getErrorPage('Missing video URL parameter'), {
                    headers: { 'Content-Type': 'text/html' },
                    status: 400
                });
            }
            
            // Try to extract filename from URL if not provided
            if (filename === 'video.mp4' && videoUrl) {
                const urlParts = videoUrl.split('/');
                const lastPart = urlParts.pop().split('?')[0];
                if (lastPart && lastPart.includes('.')) {
                    filename = decodeURIComponent(lastPart);
                }
            }
            
            const html = getPlayerHTML(videoUrl, filename);
            return new Response(html, {
                headers: { 'Content-Type': 'text/html; charset=utf-8' }
            });
        }
        
        // Stream proxy endpoint: /stream/:key - proxies file with proper range support
        if (path.startsWith('/stream/')) {
            const key = decodeURIComponent(path.substring(8));
            const accessKey = env.WASABI_ACCESS_KEY || WASABI_CONFIG.accessKey;
            const secretKey = env.WASABI_SECRET_KEY || WASABI_CONFIG.secretKey;
            const bucket = env.WASABI_BUCKET || WASABI_CONFIG.bucket;
            const region = env.WASABI_REGION || WASABI_CONFIG.region;
            
            if (!accessKey || !secretKey) {
                return new Response('Storage not configured', { status: 500 });
            }
            
            const host = `${bucket}.s3.${region}.wasabisys.com`;
            const s3Url = `https://${host}/${encodeURIComponent(key)}`;
            
            // Forward range headers for video seeking
            const rangeHeader = request.headers.get('Range');
            const headers = {
                'Host': host
            };
            
            // Simple fetch without full signature for public bucket or use presigned
            // For private buckets, you'd need full signature. This example assumes
            // the worker has access or uses presigned URLs from bot
            
            const s3Request = new Request(s3Url, {
                method: 'GET',
                headers: rangeHeader ? { 'Range': rangeHeader } : {},
                cf: { cacheTtl: 3600, cacheEverything: true }
            });
            
            try {
                const response = await fetch(s3Request);
                const newHeaders = new Headers(response.headers);
                newHeaders.set('Access-Control-Allow-Origin', '*');
                newHeaders.set('Access-Control-Expose-Headers', 'Content-Range, Accept-Ranges');
                
                return new Response(response.body, {
                    status: response.status,
                    headers: newHeaders
                });
            } catch (error) {
                return new Response(`Stream error: ${error.message}`, { status: 500 });
            }
        }
        
        // Generate presigned URL endpoint (requires auth)
        if (path === '/api/presign' && request.method === 'POST') {
            // Add your authentication check here (e.g., header token)
            const authHeader = request.headers.get('X-Auth-Token');
            if (authHeader !== env.API_TOKEN && authHeader !== 'your-secret-token') {
                return new Response('Unauthorized', { status: 401 });
            }
            
            try {
                const body = await request.json();
                const key = body.key;
                const expires = body.expires || 604800; // 7 days default
                
                if (!key) {
                    return new Response(JSON.stringify({ error: 'Missing key' }), { status: 400 });
                }
                
                const presignedUrl = await generatePresignedUrl(key, expires);
                if (presignedUrl) {
                    return new Response(JSON.stringify({ url: presignedUrl, expires }), {
                        headers: { 'Content-Type': 'application/json' }
                    });
                } else {
                    return new Response(JSON.stringify({ error: 'Failed to generate URL' }), { status: 500 });
                }
            } catch (e) {
                return new Response(JSON.stringify({ error: e.message }), { status: 500 });
            }
        }
        
        // Default 404
        return new Response('Not Found', { status: 404 });
    }
};

function getErrorPage(message) {
    return `<!DOCTYPE html>
<html>
<head><title>Playback Error</title><meta name="viewport" content="width=device-width,initial-scale=1">
<style>
body { background: #0a0c12; display: flex; justify-content: center; align-items: center; min-height: 100vh; font-family: system-ui; margin: 0; padding: 1rem; }
.card { background: #1a1e2f; padding: 2rem; border-radius: 2rem; text-align: center; max-width: 400px; }
i { font-size: 3rem; color: #f87171; margin-bottom: 1rem; display: block; }
h2 { color: white; margin-bottom: 0.5rem; }
p { color: #9ca3cf; }
button { background: #3b4f8c; color: white; border: none; padding: 0.75rem 1.5rem; border-radius: 2rem; margin-top: 1rem; cursor: pointer; }
</style>
</head>
<body>
<div class="card">
<div>🎬</div>
<h2>Cannot Load Video</h2>
<p>${escapeHtml(message)}</p>
<button onclick="history.back()">Go Back</button>
</div>
</body>
</html>`;
}